module.exports = {
    'MIT': {
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: false,
        privateUse: true,
        discloseSource: false,
        licenseAndCopyRightNotice: false,
        sameLicense: false,
        stateChange: false,
        liability: true,
        tradeMarkUse: true,
        warranty: true
    },
    'Apache-2.0':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: true,
        privateUse: true,
        discloseSource: false,
        licenseAndCopyRightNotice: true,
        sameLicense: false,
        stateChange: true,
        liability: true,
        tradeMarkUse: true,
        warranty: true
    },
    'BSD-3':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: false,
        privateUse: true,
        discloseSource: false,
        licenseAndCopyRightNotice: true,
        sameLicense: false,
        stateChange: false,
        liability: true,
        tradeMarkUse: false,
        warranty: true
    },
    'BSD-2':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: false,
        privateUse: true,
        discloseSource: false,
        licenseAndCopyRightNotice: true,
        sameLicense: false,
        stateChange: false,
        liability: true,
        tradeMarkUse: false,
        warranty: true
    },
    'GPL-3':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: true,
        privateUse: true,
        discloseSource: true,
        licenseAndCopyRightNotice: true,
        sameLicense: true,
        stateChange: true,
        liability: true,
        tradeMarkUse: false,
        warranty: true
    },
    'LGPL-3':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: true,
        privateUse: true,
        discloseSource: true,
        licenseAndCopyRightNotice: true,
        sameLicense: true,
        stateChange: true,
        liability: true,
        tradeMarkUse: false,
        warranty: true
    },
    'MPL-2.0':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: true,
        privateUse: true,
        discloseSource: true,
        licenseAndCopyRightNotice: true,
        sameLicense: true,
        stateChange: false,
        liability: true,
        tradeMarkUse: true,
        warranty: true
    },
    'CDDL-1.0':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: true,
        privateUse: true,
        discloseSource: true,
        licenseAndCopyRightNotice: true,
        sameLicense: false,
        stateChange: false,
        liability: true,
        tradeMarkUse: true,
        warranty: false
    },
    'EPL-1.0':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: true,
        privateUse: true,
        discloseSource: true,
        licenseAndCopyRightNotice: true,
        sameLicense: true,
        stateChange: false,
        liability: true,
        tradeMarkUse: false,
        warranty: true
    }
}