module.exports = {
    'MIT': {
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: false,
        privateUse: true,
        discloseSource: false,
        licenseAndCopyRightNotice: true,
        sameLicense: false,
        stateChange: false,
        liability: true,
        tradeMarkUse: false,
        warranty: true,
        description:"MIT License (MIT)"
    },
    'Apache-2.0':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: true,
        privateUse: true,
        discloseSource: false,
        licenseAndCopyRightNotice: true,
        sameLicense: false,
        stateChange: true,
        liability: true,
        tradeMarkUse: true,
        warranty: true,
        description:"Apache License 2.0 (Apache-2.0)"
    },
    'BSD-3':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: false,
        privateUse: true,
        discloseSource: false,
        licenseAndCopyRightNotice: true,
        sameLicense: false,
        stateChange: false,
        liability: true,
        tradeMarkUse: false,
        warranty: true,
        description:"3-Clause BSD License (BSD-3-Clause)"
    },
    'BSD-2':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: false,
        privateUse: true,
        discloseSource: false,
        licenseAndCopyRightNotice: true,
        sameLicense: false,
        stateChange: false,
        liability: true,
        tradeMarkUse: false,
        warranty: true,
        description:"2-Clause BSD License (BSD-2-Clause"
    },
    'GPL-3':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: true,
        privateUse: true,
        discloseSource: true,
        licenseAndCopyRightNotice: true,
        sameLicense: true,
        stateChange: true,
        liability: true,
        tradeMarkUse: false,
        warranty: true,
        description:"GNU General Publice License v3 (GPL-3)"
    },
    'LGPL-3':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: true,
        privateUse: true,
        discloseSource: true,
        licenseAndCopyRightNotice: true,
        sameLicense: true,
        stateChange: true,
        liability: true,
        tradeMarkUse: false,
        warranty: true,
        description:"GNU Lesser General Public License v3 (LGPL-3.0)"
    },
    'MPL-2.0':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: true,
        privateUse: true,
        discloseSource: true,
        licenseAndCopyRightNotice: true,
        sameLicense: true,
        stateChange: false,
        liability: true,
        tradeMarkUse: true,
        warranty: true,
        description:"Mozilla Publice License 2.0 (MPL-2.0)"
    },
    'CDDL-1.0':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: true,
        privateUse: true,
        discloseSource: true,
        licenseAndCopyRightNotice: true,
        sameLicense: false,
        stateChange: false,
        liability: true,
        tradeMarkUse: true,
        warranty: false,
        description:"Common Development and Distribution License v1.0 (CDDL-1.0)"
    },
    'EPL-1.0':{
        commercialUse: true,
        destribution: true,
        modification: true,
        patentUse: true,
        privateUse: true,
        discloseSource: true,
        licenseAndCopyRightNotice: true,
        sameLicense: true,
        stateChange: false,
        liability: true,
        tradeMarkUse: false,
        warranty: true,
        description:"Eclipse Public License v1.0 (EPL-1.0)"
    }
}